name: StagingUpdate
on:
  push:
    branches:
      - 'staging*'

env:
  WORK_DIR: cd /root/sites/wishket.com/source
  REMOVE_DOCKER: docker rm -f $(docker ps -a -q --filter="name=${GITHUB_REF##*/}")
  PATH_SET: export PATH=${{ secrets.PYPATH }}
  KILL_GUNICORN: pkill -e gunicorn

#      SET_REF: if [ ${{ github.event_name }} == 'pull_request' ]; then GITHUB_REF=${{ github.head_ref }}; else GITHUB_REF=${{ github.ref }}; fi
  SET_REF: GITHUB_REF=${{ github.ref }};

  GIT_FETCH: git fetch origin
  GIT_CHECKOUT: git checkout ${GITHUB_REF##*/}
  GIT_PULL: git pull

  START_GUNICORN: sudo ~/.pyenv/versions/service3/bin/gunicorn -c gunicorn.py wishket.wsgi:application &> /dev/null &
  COPY_STATIC_FOLDER: cp -r /root/sites/wishket.com/source/wishket/static/ /root/sites/wishket.com/
  DOCKER_SET: sudo ~/.pyenv/versions/service3/bin/fab docker_set:t,t

jobs:
  build:
    name: chs-staging
    runs-on: ubuntu-18.04
    steps:
    - name: Start staging update
      uses: fifsky/ssh-action@master
      with:
        command: |
          ${{ env.SET_REF }}
          ${{ env.WORK_DIR }}
          python --version
          pip freeze

          ${{ env.DOCKER_SET }}

        host: ssh.chs.wishdev.net
        user: root
        key: ${{ secrets.GIMO_PRIVATEKEY }}
