name: StagingUpdate
on:
  push:
    branches:
      - 'staging*'
env:
  WORK_DIR: cd /root/sites/wishket.com/source
  REMOVE_DOCKER: docker rm -f $(docker ps -a -q --filter="name=${GITHUB_REF##*/}")
  KILL_GUNICORN: pkill -e gunicorn

  SET_REF: GITHUB_REF=${{ github.ref }};

  GIT_FETCH: git fetch origin
  GIT_CHECKOUT: git checkout ${GITHUB_REF##*/}
  GIT_PULL: git pull

  START_GUNICORN: sudo ~/.pyenv/versions/service/bin/gunicorn -c gunicorn.py wishket.wsgi:application &> /dev/null &
  COPY_STATIC_FOLDER: cp -r /root/sites/wishket.com/source/wishket/static/ /root/sites/wishket.com/
  DOCKER_SET: /root/.pyenv/versions/service/bin/fab docker_set:t,t

jobs:
  pylint:
    name: Start lint in local
    runs-on: ubuntu-latest
    steps:
      - name: Start pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        with:
          args: pip install . ; pylint **/*.py"
