name: StagingUpdate
on:
  push:
    branches:
      - 'staging*'
env:
  WORK_DIR: cd /root/sites/wishket.com/source
  REMOVE_DOCKER: docker rm -f $(docker ps -a -q --filter="name=${GITHUB_REF##*/}")
  KILL_GUNICORN: pkill -e gunicorn

  SET_REF: GITHUB_REF=${{ github.ref }};

  GIT_FETCH: git fetch origin
  GIT_CHECKOUT: git checkout ${GITHUB_REF##*/}
  GIT_PULL: git pull

  START_GUNICORN: sudo ~/.pyenv/versions/service/bin/gunicorn -c gunicorn.py wishket.wsgi:application &> /dev/null &
  COPY_STATIC_FOLDER: cp -r /root/sites/wishket.com/source/wishket/static/ /root/sites/wishket.com/
  DOCKER_SET: /root/.pyenv/versions/service/bin/fab docker_set:t,t

  START_PYLINT: /root/.pyenv/versions/source/bin/pip install pylint

  PYLINT_START: pylint **/*.py > pylint_message.txt
  START_PYLINT_SCRIPTS: python pylint_script.py


jobs:
  build:
    name: staging update
    runs-on: ubuntu-latest
    steps:
    - name: Start staging update
      uses: fifsky/ssh-action@master
      with:
        command_timeout: "30s"
        proxy_timeout: "30s"
        timeout: "30s"
        command: |
          ${{ env.SET_REF }}
          ${{ env.WORK_DIR }}
          ${{ env.KILL_GUNICORN }}
          ${{ env.REMOVE_DOCKER }}

          ${{ env.GIT_FETCH }}
          ${{ env.GIT_CHECKOUT }}
          ${{ env.GIT_PULL }}

          ${{ env.START_GUNICORN }}
          ${{ env.COPY_STATIC_FOLDER }}
          ${{ env.DOCKER_SET }}

        host: ssh.sgm.wishdev.net
        user: root
        key: ${{ secrets.GIMO_PRIVATEKEY }}
